#!/usr/bin/env python3
"""session-catalog — READ-ONLY multi-harness AI session catalog.

Capability 1 (this tool): catalog historical session artifacts of several AI harnesses
into ONE normalized, private index of pointers and metadata. Sources are opened
read-only, SQLite is never opened, nothing touches the network, and outputs go only to
a private directory outside any git work tree.

Capability 2 (live attach / adopt / resume of a RUNNING session) is intentionally NOT
implemented: it can mutate harness state and needs its own gate. Discovering a
transcript never authorizes driving that session.

Session content is untrusted DATA, never instructions. Control envelopes, hidden
reasoning, tool payloads and attachments are dropped at ingestion; secrets and PII are
redacted at ingestion, before text can reach any output, log or error.

Subcommands
  stores   per-store capability matrix (metadata only; fail-closed status)
  index    pass 1: metadata/pointer inventory (no text) + exhaustiveness receipt
  extract  pass 2: stream sanitized, topic-scoped messages to stdout (nothing persisted
           except the receipt, quarantine and security findings)

Stdlib only; Python >= 3.9.
"""
from __future__ import annotations

import argparse
import fnmatch
import getpass
import hashlib
import hmac
import io
import json
import math
import os
import re
import secrets
import sys
import time
import unicodedata
import zipfile
from collections import Counter, OrderedDict, defaultdict
from datetime import datetime, timezone
from typing import Callable, Dict, Iterator, List, Optional, Tuple

SCHEMA = "session-catalog/v1"
MARKER = ".session-catalog-output"   # dropped in every output dir; discovery never descends into it
SAMPLE_UNITS = 3
ENCRYPTED_ENTROPY = 7.5              # bits/byte; JSON/markdown sit well below 6
LIMITS = {"max_file_bytes": 512 << 20, "max_record_bytes": 16 << 20, "max_files": 50000,
          "max_records": 20_000_000}
IGNORED_SUFFIXES = ("-wal", "-shm", "-journal", ".lock", ".tmp", ".partial", ".part", ".swp", "~")
_PRUNE_DIRS = re.compile(r"(?i)^(?:\.git|node_modules|Mobile Documents|CloudStorage|Dropbox|Google Drive|OneDrive|"
                         r"iCloud Drive|Backups\.backupdb|\.Trash|.*\.backup|.*-backup|Time Machine.*)$")

# ── ingestion sanitizer: controls → envelopes → redaction ──────────────────

_ANSI = re.compile(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)|\x1b\[[0-?]*[ -/]*[@-~]|\x1b[@-Z\\-_]")
_CONTROLS = re.compile(r"[\x00-\x08\x0b-\x1f\x7f-\x9f\u200b-\u200f\u202a-\u202e\u2060-\u2069\ufeff]")

# Harness-injected control envelopes. Their bodies are not the human's words and may
# carry directives aimed at the ORIGINAL agent — never at a reader of the transcript.
ENVELOPE_TAGS = (
    "system-reminder", "system-notice", "system", "irc", "command-name", "command-message",
    "command-args", "command-contents", "local-command-stdout", "local-command-stderr",
    "local-command-caveat", "environment_context", "user_instructions", "INSTRUCTIONS",
    "user-prompt-submit-hook", "task-notification", "task-result", "skill", "skill-content",
    "available-skills", "bash-input", "bash-stdout", "bash-stderr", "tool_result",
    "function_results", "turn_aborted", "ide_opened_file", "ide_selection",
    "persisted-output", "post-tool-use-hook", "hook_output", "attachments",
    "permissions instructions", "collaboration_mode", "memory", "subagent_notification",
)
_ENV_BLOCK = re.compile(r"<(" + "|".join(map(re.escape, ENVELOPE_TAGS)) + r")(?:\s[^>]*)?>[\s\S]*?</\1\s*>")
_ENV_SELF = re.compile(r"<(?:" + "|".join(map(re.escape, ENVELOPE_TAGS)) + r")(?:\s[^>]*)?/>")
_WHOLE_TAG = re.compile(r"^\s*<([A-Za-z_][\w -]*)(?:\s[^>]*)?>[\s\S]*</\1\s*>\s*$")
_INJECTED_PREFIXES = (
    "# AGENTS.md instructions for", "Base directory for this skill:",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user",
)

_SECRET_WORDS = (r"password|passwd|pwd|secret|client[_-]?secret|api[_-]?key|apikey|access[_-]?key|"
                 r"secret[_-]?key|private[_-]?key|access[_-]?token|refresh[_-]?token|session[_-]?token|"
                 r"auth[_-]?token|token|credentials?")
# (label, is_credential, pattern) — order matters: specific formats before generic ones.
REDACTIONS: List[Tuple[str, bool, re.Pattern]] = [
    ("private-key", True, re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?(?:-----END [A-Z ]*PRIVATE KEY-----|$)")),
    ("github-token", True, re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{22,})")),
    ("api-key", True, re.compile(r"\bsk-(?:ant-|proj-)?[A-Za-z0-9_\-]{20,}")),
    ("aws-key", True, re.compile(r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b")),
    ("slack-token", True, re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}")),
    ("google-key", True, re.compile(r"\bAIza[0-9A-Za-z_\-]{35}\b")),
    ("1password-token", True, re.compile(r"\bops_[A-Za-z0-9]{20,}")),
    ("jwt", True, re.compile(r"\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}")),
    ("auth-header", True, re.compile(
        r"(?im)\b(authorization|proxy-authorization|x-api-key|api-key|x-auth-token|cookie|set-cookie)"
        r"(\s*[:=]\s*)[^\r\n]+")),
    ("bearer", True, re.compile(r"(?i)\b(?:bearer|basic)\s+[A-Za-z0-9._~+/=\-]{12,}")),
    ("url-credentials", True, re.compile(r"(?<=://)[^/\s:@]+:[^/\s@]+@")),
    ("url-secret-param", True, re.compile(
        r"(?i)([?&](?:" + _SECRET_WORDS + r"|sig|signature|code|key|auth|x-amz-signature|x-amz-credential)=)[^&#\s]+")),
    ("assignment", True, re.compile(
        r"(?i)\b(" + _SECRET_WORDS + r")([\"']?\s*[:=]\s*)([\"']?)[^\s\"',;]{6,}\3")),
    ("opaque-blob", True, re.compile(r"[A-Za-z0-9+/_-]{40,}={0,2}")),
    ("op-ref", False, re.compile(r"\bop://[^\s'\"`)]+")),
    ("email", False, re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")),
    ("cpf", False, re.compile(r"\b\d{3}\.\d{3}\.\d{3}-\d{2}\b")),
    ("phone", False, re.compile(r"(?<![\w.])\+\d{10,15}\b")),
]
_HOME_PATH = re.compile(r"(?:/Users|/home)/[^/\s'\"`]+")


def _blob_like(s: str) -> bool:
    """Base64-ish secret material: mixed case AND digits AND dense. Hex SHAs (no upper
    case) and ordinary slash paths (mostly lower case) do not qualify."""
    up, lo, dg = sum(c.isupper() for c in s), sum(c.islower() for c in s), sum(c.isdigit() for c in s)
    return bool(up and lo and dg) and (up + dg) / len(s) >= 0.3


def clean(text: str) -> str:
    """NFC-normalize and drop ANSI/OSC escapes, control and bidi-override characters."""
    text = unicodedata.normalize("NFC", text)
    return _CONTROLS.sub("", _ANSI.sub("", text))


def strip_envelopes(text: str) -> str:
    out = _ENV_SELF.sub("", _ENV_BLOCK.sub("", text))
    return "" if any(out.lstrip().startswith(p) for p in _INJECTED_PREFIXES) else out.strip()


_PLACEHOLDER = re.compile(r"(?i)^(?:[$<{%\[(]|\*+$|x{3,}|\.{3}|changeme|redacted|example|your[_-]|dummy|test|"
                          r"placeholder|secret$|token$|password$|none$|null$|true$|false$|env\b|process\.env|os\.environ)")
_STRONG = {"private-key", "github-token", "api-key", "aws-key", "slack-token", "google-key", "1password-token", "jwt"}


def credible(value: str) -> bool:
    """A redacted value counts as a PROBABLE credential (security finding) only when it
    is not a placeholder and mixes character classes. Everything matched is redacted anyway."""
    v = value.strip().strip("'\"")
    if len(v) < 8 or _PLACEHOLDER.match(v):
        return False
    return sum((any(c.isupper() for c in v), any(c.islower() for c in v), any(c.isdigit() for c in v))) >= 2


def redact(text: str) -> Tuple[str, Counter, Counter]:
    """Returns (redacted text, all hits by label, probable-credential hits by label)."""
    hits: Counter = Counter()
    creds: Counter = Counter()

    def sub(label: str, keep_prefix: Callable[[re.Match], str], value: Callable[[re.Match], str],
            tag: str) -> Callable[[re.Match], str]:
        def fn(m: re.Match) -> str:
            if label == "opaque-blob" and not _blob_like(m.group(0)):
                return m.group(0)
            hits[label] += 1
            if label in _STRONG or (label not in ("opaque-blob", "op-ref", "email", "cpf", "phone")
                                    and credible(value(m))):
                creds[label] += 1
            return keep_prefix(m) + "[REDACTED:" + tag + "]"
        return fn

    whole = lambda m: m.group(0)  # noqa: E731
    none = lambda m: ""  # noqa: E731
    for label, _cred, rx in REDACTIONS:
        if label == "assignment":
            fn = sub(label, lambda m: m.group(1) + m.group(2), lambda m: m.group(0)[len(m.group(1) + m.group(2)):],
                     "secret")
        elif label == "auth-header":
            fn = sub(label, lambda m: m.group(1) + m.group(2), lambda m: m.group(0)[len(m.group(1) + m.group(2)):]
                     .split()[-1] if m.group(0)[len(m.group(1) + m.group(2)):].split() else "", "auth-header")
        elif label == "url-secret-param":
            fn = sub(label, lambda m: m.group(1), lambda m: m.group(0)[len(m.group(1)):], "secret")
        elif label == "url-credentials":
            fn = sub(label, none, lambda m: m.group(0).split(":", 1)[-1].rstrip("@"), "credentials")
            fn = (lambda f: lambda m: f(m).replace("[REDACTED:credentials]", "[REDACTED:credentials]@"))(fn)
        elif label == "bearer":
            fn = sub(label, none, lambda m: m.group(0).split()[-1], label)
        else:
            fn = sub(label, none, whole, label)
        text = rx.sub(fn, text)
    return _HOME_PATH.sub("~", text), hits, creds



def ident(s: str, n: int = 64) -> str:
    """Schema tokens (tool names, record types) as safe identifiers — never free text."""
    return re.sub(r"[^A-Za-z0-9_.:-]", "", clean(str(s or "")))[:n] or "unknown"


# ── helpers ────────────────────────────────────────────────────────────────

def iso(ts) -> Optional[str]:
    if ts is None or ts == "":
        return None
    try:
        if isinstance(ts, (int, float)) or (isinstance(ts, str) and re.fullmatch(r"\d+(\.\d+)?", ts)):
            v = float(ts)
            dt = datetime.fromtimestamp(v / 1000.0 if v > 1e12 else v, tz=timezone.utc)
        else:
            s = str(ts).strip().replace(" ", "T", 1)
            s = s[:-1] + "+00:00" if s.endswith("Z") else s
            s = re.sub(r"(\.\d{6})\d+", r"\1", s)
            dt = datetime.fromisoformat(s)
            dt = dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt
        return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    except (ValueError, OverflowError, OSError):
        return None


def entropy(b: bytes) -> float:
    n = len(b)
    return -sum(c / n * math.log2(c / n) for c in Counter(b).values()) if n else 0.0


def looks_binary(head: bytes) -> bool:
    if not head:
        return False
    if b"\x00" in head:
        return True
    bad = head.decode("utf-8", "replace").count("\ufffd")
    return bad / max(1, len(head)) > 0.05


def blocks_text(content) -> str:
    if isinstance(content, str):
        return content
    parts = []
    for b in content if isinstance(content, list) else [content]:
        if isinstance(b, str):
            parts.append(b)
        elif isinstance(b, dict) and b.get("type") in (None, "text", "input_text", "output_text") \
                and isinstance(b.get("text"), str):
            parts.append(b["text"])
    return "\n".join(parts)


_ATTACHMENT_BLOCKS = {"image": "image", "input_image": "image", "image_url": "image", "document": "document",
                      "file": "file", "input_file": "file", "inlineData": "inline-data", "fileData": "file"}


def attachment_kinds(content) -> List[str]:
    out = []
    for b in content if isinstance(content, list) else []:
        if isinstance(b, dict):
            k = _ATTACHMENT_BLOCKS.get(b.get("type")) or next((v for k, v in _ATTACHMENT_BLOCKS.items() if k in b), None)
            if k:
                out.append(k)
    return out


# ── run context: gates, receipts, quarantine, security findings ────────────

class Ctx:
    def __init__(self, home: str, high_water: float, limits: dict, exclude_globs: List[str], key: bytes):
        self.home, self.high_water, self.limits = home, high_water, limits
        self.exclude_globs = [os.path.expanduser(g) for g in exclude_globs]
        self.key = key
        self.excluded_roots: List[str] = []
        self.receipt: Dict[str, Counter] = defaultdict(Counter)
        self.quarantine: List[dict] = []
        self.findings: Dict[tuple, dict] = {}
        self.sources: Dict[str, str] = {}
        self.files_admitted = 0
        self.records_total = 0

    def opaque(self, prefix: str, value: str) -> str:
        return prefix + hmac.new(self.key, value.encode("utf-8", "replace"), hashlib.sha256).hexdigest()[:16]

    def source_id(self, path: str) -> str:
        sid = self.opaque("src-", path)
        self.sources[sid] = rel(self.home, path)
        return sid

    def quarantine_(self, store: str, path: str, reason: str, line: Optional[int] = None):
        self.receipt[store]["records_quarantined" if line is not None else "files_quarantined"] += 1
        self.quarantine.append({"store": store, "source_id": self.source_id(path), "line": line, "reason": reason})

    def excluded(self, path: str) -> bool:
        rp = os.path.realpath(path)
        if any(rp == r or rp.startswith(r + os.sep) for r in self.excluded_roots):
            return True
        return any(fnmatch.fnmatch(path, g) or fnmatch.fnmatch(rp, g) for g in self.exclude_globs)

    def walk(self, store: str, root: str, keep: Callable[[str, str], bool]) -> List[str]:
        """Enumerate canonical files under root: no directory symlinks, realpath-confined."""
        out: List[str] = []
        real_root = os.path.realpath(root)
        if not os.path.isdir(root):
            return out
        for d, dirs, files in os.walk(root, followlinks=False):
            for sub in list(dirs):
                full = os.path.join(d, sub)
                if os.path.islink(full):
                    dirs.remove(sub)
                    self.receipt[store]["dir_symlinks_refused"] += 1
                elif self.excluded(full) or os.path.exists(os.path.join(full, MARKER)):
                    dirs.remove(sub)
                    self.receipt[store]["dirs_excluded"] += 1
                elif os.path.exists(os.path.join(full, ".git")) or _PRUNE_DIRS.search(sub):
                    dirs.remove(sub)  # git repos, cloud-sync folders and backups are never traversed
                    self.receipt[store]["dirs_pruned_repo_sync_or_backup"] += 1
            for f in files:
                full = os.path.join(d, f)
                if f.endswith(IGNORED_SUFFIXES):
                    continue
                if not keep(os.path.relpath(full, root), f):
                    continue
                rp = os.path.realpath(full)
                if not (rp == real_root or rp.startswith(real_root + os.sep)):
                    self.receipt[store]["files_refused_outside_root"] += 1
                    continue
                out.append(full)
        return sorted(out)

    def admit(self, store: str, path: str, whole_record: bool = False, sniff: bool = True) -> Optional[os.stat_result]:
        """File-level gate. Returns the stat to re-check after reading, or None (counted)."""
        rc = self.receipt[store]
        rc["files_seen"] += 1
        if self.excluded(path):
            rc["files_excluded"] += 1
            return None
        try:
            st = os.stat(path)
        except OSError:
            self.quarantine_(store, path, "stat-failed")
            return None
        if st.st_mtime >= self.high_water:
            rc["files_deferred_live_or_unstable"] += 1
            return None
        cap = self.limits["max_record_bytes"] if whole_record else self.limits["max_file_bytes"]
        if st.st_size > cap:
            self.quarantine_(store, path, "file-over-size-cap")
            return None
        if self.files_admitted >= self.limits["max_files"]:
            self.quarantine_(store, path, "run-file-cap")
            return None
        with open(path, "rb") as fh:
            if sniff and looks_binary(fh.read(8192)):
                self.quarantine_(store, path, "binary-content")
                return None
        self.files_admitted += 1
        return st

    def unchanged(self, store: str, path: str, st: os.stat_result) -> bool:
        try:
            now = os.stat(path)
        except OSError:
            now = None
        if not now or (now.st_size, now.st_mtime) != (st.st_size, st.st_mtime):
            self.receipt[store]["files_deferred_live_or_unstable"] += 1
            return False
        return True

    def jsonl(self, store: str, path: str) -> Iterator[Tuple[int, dict]]:
        """Stream records line by line; oversize/malformed/non-object lines are quarantined."""
        cap = self.limits["max_record_bytes"]
        with open(path, "rb") as fh:
            lineno = 0
            while True:
                chunk = fh.readline(cap + 1)
                if not chunk:
                    break
                lineno += 1
                if len(chunk) > cap and not chunk.endswith(b"\n"):
                    while chunk and not chunk.endswith(b"\n"):  # drain the rest of the oversized record
                        chunk = fh.readline(cap + 1)
                    self.quarantine_(store, path, "record-over-size-cap", lineno)
                    continue
                if not chunk.strip():
                    continue
                if self.records_total >= self.limits["max_records"]:
                    self.quarantine_(store, path, "run-record-cap", lineno)
                    return
                self.records_total += 1
                try:
                    obj = json.loads(chunk)
                except ValueError:
                    self.quarantine_(store, path, "malformed-json", lineno)
                    continue
                if not isinstance(obj, dict):
                    self.quarantine_(store, path, "non-object-record", lineno)
                    continue
                self.receipt[store]["records_parsed"] += 1
                yield lineno, obj

    def unknown(self, store: str, path: str, lineno: int, rtype) -> None:
        self.quarantine_(store, path, "unknown-record-type:" + ident(rtype, 40), lineno)


class Emit:
    """Builds normalized message dicts, sanitizing text AT INGESTION. Roles stay distinct
    (user · assistant · tool_call · tool_result · system · developer · provider_event); tool
    calls keep only name + status, never arguments; hidden reasoning never enters."""

    def __init__(self, ctx: Ctx, store: "Store", path: str, cwd: Optional[str] = None):
        self.ctx, self.store, self.path = ctx, store, path
        self.cwd = cwd  # cwd in effect NOW — sessions change directory midway
        self.msgs: List[dict] = []

    def _add(self, role: str, kind: str, text: str, ts, line: int, tool: Optional[str], redactions: int, **extra):
        self.msgs.append(dict({"role": role, "kind": kind, "text": text, "ts": iso(ts), "tool": tool,
                               "line": line, "redactions": redactions, "cwd": self.cwd}, **extra))

    def text(self, role: str, text, ts, line: int, kind: str = "text", label: Optional[str] = None):
        raw = text if isinstance(text, str) else ""
        t = strip_envelopes(clean(raw))
        if role == "user" and _WHOLE_TAG.match(t or ""):
            t = ""
        t, hits, creds = redact(t) if t else ("", Counter(), Counter())
        for lab in creds:  # probable credentials only; placeholders are redacted but not reported
            key = (self.path, lab)
            if key not in self.ctx.findings:
                self.ctx.findings[key] = {
                    "vendor": self.store.provider, "store": self.store.id,
                    "source_id": self.ctx.source_id(self.path), "credential_type": lab,
                    "detected_at": iso(ts), "recommendation": "rotation recommended"}
        if t:
            self._add(role, kind, t, ts, line, label, sum(hits.values()))
        else:
            self.drop(ts, line, dialogue=True)

    def tool_call(self, ts, line: int, name, status: Optional[str] = None):
        self._add("tool_call", "tool_call", "", ts, line, ident(name) if name else "unknown", 0, status=status)

    def tool_result(self, ts, line: int, is_error=None):
        status = None if is_error is None else ("error" if is_error else "ok")
        self._add("tool_result", "tool_result", "", ts, line, None, 0, status=status)

    def event(self, role: str, kind: str, ts, line: int, tool: Optional[str] = None):
        self._add(role, kind, "", ts, line, ident(tool) if tool else None, 0)

    def drop(self, ts, line: int, dialogue: bool = False, role: str = "system"):
        """`dialogue` marks a recognized user/assistant record whose text was all envelope."""
        self._add(role, "dropped", "", ts, line, None, 0, dialogue=dialogue)

    def attachments(self, role: str, content, ts, line: int):
        for k in attachment_kinds(content):
            self.event(role, "attachment", ts, line, k)


# ── adapters (one per on-disk format; verified versions documented in SKILL.md) ──

CLAUDE_PARSED = {"user", "assistant"}
CLAUDE_IGNORED = {"attachment", "last-prompt", "mode", "atis-latch", "pr-link", "bridge-session", "ai-title",
                  "custom-title", "permission-mode", "queue-operation", "system", "agent-name", "worktree-state",
                  "relocated", "agent-setting", "file-history-snapshot", "file-history-delta", "cost-state",
                  "started", "result", "fork-context-ref", "continued-in", "summary", "tag", "progress"}


def load_claude(ctx: Ctx, store: "Store", path: str, default_client: str) -> tuple:
    sub = "/subagents/" in path.replace(os.sep, "/")
    meta = {"session_id": None, "cwd": None, "client": None, "kind": "subagent" if sub else "main"}
    e = Emit(ctx, store, path)
    for ln, r in ctx.jsonl(store.id, path):
        t = r.get("type")
        if t not in CLAUDE_PARSED:
            if t not in CLAUDE_IGNORED:
                ctx.unknown(store.id, path, ln, t)
            continue
        v = str(r.get("version") or "")
        if v and not v.startswith("2."):
            ctx.quarantine_(store.id, path, "unverified-format-version", ln)
            continue
        meta["session_id"] = meta["session_id"] or r.get("sessionId")
        meta["cwd"] = meta["cwd"] or r.get("cwd")
        e.cwd = r.get("cwd") or e.cwd
        if meta["client"] is None and r.get("entrypoint"):
            ep = str(r["entrypoint"])
            meta["client"] = {"cli": "anthropic.claude-code", "claude-desktop": "anthropic.claude-desktop"}.get(
                ep, "anthropic.claude-sdk" if ep.startswith("sdk") else default_client)
        ts = r.get("timestamp")
        if r.get("isMeta") or r.get("isCompactSummary"):
            e.drop(ts, ln)
            continue
        content = (r.get("message") or {}).get("content")
        if t == "user":
            if isinstance(content, list) and any(isinstance(b, dict) and b.get("type") == "tool_result" for b in content):
                e.tool_result(ts, ln, any(isinstance(b, dict) and b.get("is_error") for b in content))
                continue
            e.text("user", blocks_text(content), ts, ln)
            e.attachments("user", content, ts, ln)
        else:
            for b in content if isinstance(content, list) else [{"type": "text", "text": content}]:
                if isinstance(b, dict) and b.get("type") == "text":
                    e.text("assistant", b.get("text"), ts, ln)
                elif isinstance(b, dict) and b.get("type") in ("tool_use", "server_tool_use"):
                    e.tool_call(ts, ln, b.get("name"))
    stem = os.path.splitext(os.path.basename(path))[0]
    meta["session_id"] = str(meta["session_id"] or stem)
    if sub:  # subagent files reuse the parent's sessionId; keep the ids distinct
        meta["parent_session_id"] = meta["session_id"]
        meta["session_id"] = meta["session_id"] + "/" + stem
    meta["client"] = meta["client"] or default_client
    return meta, e.msgs


CODEX_RECORDS = {"session_meta", "response_item", "event_msg", "turn_context", "token_usage_record",
                 "world_state", "compacted", "inter_agent_communication_metadata", "token_usage"}
CODEX_ITEMS_IGNORED = {"reasoning", "agent_message", "tool_search_output"}
CODEX_CALLS = {"function_call", "custom_tool_call", "local_shell_call", "web_search_call", "tool_search_call"}
CODEX_CLIENTS = {"Codex Desktop": "openai.codex-app", "codex_work_desktop": "openai.codex-app",
                 "codex-tui": "openai.codex-cli", "codex_cli_rs": "openai.codex-cli", "codex_exec": "openai.codex-exec",
                 "codex_vscode": "openai.codex-ide", "codex_sdk_ts": "openai.codex-sdk"}


def load_codex(ctx: Ctx, store: "Store", path: str, imported: Dict[str, str]) -> tuple:
    meta = {"session_id": None, "cwd": None, "client": "openai.codex-other", "kind": "main"}
    e = Emit(ctx, store, path)
    for ln, r in ctx.jsonl(store.id, path):
        t, ts = r.get("type"), r.get("timestamp")
        if t == "turn_context" and isinstance(r.get("payload"), dict) and r["payload"].get("cwd"):
            e.cwd = r["payload"]["cwd"]  # the working directory can change per turn
        p = r.get("payload") if isinstance(r.get("payload"), dict) else {}
        if t not in CODEX_RECORDS:
            ctx.unknown(store.id, path, ln, t)
            continue
        if t == "session_meta":
            if not str(p.get("cli_version") or "0.").startswith("0."):
                ctx.quarantine_(store.id, path, "unverified-format-version", ln)
                return None, []
            meta["session_id"] = meta["session_id"] or p.get("id")
            meta["cwd"] = meta["cwd"] or p.get("cwd")
            e.cwd = p.get("cwd") or e.cwd
            orig = str(p.get("originator") or "")
            meta["client"] = CODEX_CLIENTS.get(orig, "openai.codex-other")
            if isinstance(p.get("source"), dict) and "subagent" in p["source"]:
                meta["kind"] = "subagent"
            continue
        if t != "response_item":
            continue  # event_msg duplicates response_item dialogue; the rest is harness state
        pt = p.get("type")
        if pt == "message":
            if p.get("role") in ("user", "assistant"):
                e.text(p["role"], blocks_text(p.get("content")), ts, ln)
                e.attachments(p["role"], p.get("content"), ts, ln)
            else:
                e.drop(ts, ln, role="developer" if p.get("role") == "developer" else "system")
        elif pt in CODEX_CALLS:
            e.tool_call(ts, ln, p.get("name") or pt, p.get("status"))
        elif isinstance(pt, str) and pt.endswith("_output"):
            e.tool_result(ts, ln)
        elif pt in CODEX_ITEMS_IGNORED:
            e.drop(ts, ln)
        else:
            ctx.unknown(store.id, path, ln, "response_item." + str(pt))
    meta["session_id"] = str(meta["session_id"] or os.path.splitext(os.path.basename(path))[0])
    meta["imported_from"] = imported.get(meta["session_id"])
    return meta, e.msgs


PI_IGNORED = {"custom", "model_change", "title", "title_change", "thinking_level_change", "credential_pin",
              "reset_boundary", "model_usage", "session_init", "agent_status", "child_usage_attributed",
              "session_state", "git_state", "session_info", "service_tier_change", "ttsr_injection",
              "branch_summary", "label"}


def load_pi(ctx: Ctx, store: "Store", path: str, client: str, subagent: bool) -> tuple:
    """pi-mono session format v3 (omp, prime-agent)."""
    meta = {"session_id": None, "cwd": None, "client": client, "kind": "subagent" if subagent else "main"}
    e = Emit(ctx, store, path)
    for ln, r in ctx.jsonl(store.id, path):
        t = r.get("type")
        if t == "session":
            if r.get("version") not in (3, "3"):
                ctx.quarantine_(store.id, path, "unverified-format-version", ln)
                return None, []
            meta["session_id"] = meta["session_id"] or r.get("id")
            meta["cwd"] = meta["cwd"] or r.get("cwd")
            e.cwd = r.get("cwd") or e.cwd
            continue
        if t in ("custom_message", "compaction"):
            e.drop(r.get("timestamp"), ln)  # injected skill/system bodies and derived summaries
            continue
        if t in PI_IGNORED:
            continue
        if t != "message":
            ctx.unknown(store.id, path, ln, t)
            continue
        m = r.get("message") if isinstance(r.get("message"), dict) else {}
        role, ts, content = m.get("role"), r.get("timestamp") or m.get("timestamp"), m.get("content")
        if role == "user":
            e.text("user", blocks_text(content), ts, ln)
            e.attachments("user", content, ts, ln)
        elif role == "assistant":
            for b in content if isinstance(content, list) else [{"type": "text", "text": content}]:
                if isinstance(b, dict) and b.get("type") == "text":
                    e.text("assistant", b.get("text"), ts, ln)
                elif isinstance(b, dict) and b.get("type") == "toolCall":
                    e.tool_call(ts, ln, b.get("name"))
        elif role == "toolResult":
            e.tool_result(ts, ln, m.get("isError"))
        elif role in ("developer", "system"):
            e.drop(ts, ln, role=role)
        elif role == "bashExecution":  # operator-run shell command + output: provider event, no text
            e.drop(ts, ln, role="provider_event")
        else:
            ctx.unknown(store.id, path, ln, "message." + str(role))
    meta["session_id"] = str(meta["session_id"] or os.path.splitext(os.path.basename(path))[0])
    return meta, e.msgs


GEMINI_TYPES = {"user", "gemini", "info", "warning", "error"}


def _gemini_msg(ctx: Ctx, e: Emit, store: "Store", path: str, m: dict, ln: int):
    t, ts, content = m.get("type"), m.get("timestamp"), m.get("content")
    if t not in GEMINI_TYPES:
        ctx.unknown(store.id, path, ln, t)
    elif t == "user":
        e.text("user", content if isinstance(content, str) else blocks_text(content), ts, ln)
        e.attachments("user", content, ts, ln)
    elif t == "gemini":
        e.text("assistant", content if isinstance(content, str) else blocks_text(content), ts, ln)
        for tc in m.get("toolCalls") or []:
            e.tool_call(ts, ln, (tc or {}).get("name") if isinstance(tc, dict) else None,
                        (tc or {}).get("status") if isinstance(tc, dict) else None)
    else:
        e.drop(ts, ln)


def load_gemini(ctx: Ctx, store: "Store", path: str, cwd: Optional[str]) -> tuple:
    meta = {"session_id": None, "cwd": cwd, "client": "google.gemini-cli", "kind": "main"}
    e = Emit(ctx, store, path, cwd)
    records: "OrderedDict[str, Tuple[int, dict]]" = OrderedDict()
    if path.endswith(".json"):
        with open(path, "rb") as fh:
            try:
                doc = json.load(fh)
            except ValueError:
                ctx.quarantine_(store.id, path, "malformed-json", 1)
                return None, []
        if not isinstance(doc, dict) or not isinstance(doc.get("messages"), list) or "sessionId" not in doc:
            ctx.quarantine_(store.id, path, "unknown-document-shape", 1)
            return None, []
        ctx.receipt[store.id]["records_parsed"] += 1
        meta["session_id"] = doc.get("sessionId")
        meta["kind"] = "subagent" if doc.get("kind") == "subagent" else "main"
        for i, m in enumerate(doc["messages"]):
            if isinstance(m, dict):
                records[str(m.get("id", i))] = (1, m)
    else:
        for ln, r in ctx.jsonl(store.id, path):
            if "$set" in r and isinstance(r["$set"], dict):
                if isinstance(r["$set"].get("messages"), list):
                    records = OrderedDict((str(m.get("id", i)), (ln, m)) for i, m in enumerate(r["$set"]["messages"])
                                          if isinstance(m, dict))
            elif "$rewindTo" in r:
                keys = list(records)
                if r["$rewindTo"] in keys:
                    for k in keys[keys.index(r["$rewindTo"]):]:
                        records.pop(k, None)
            elif "sessionId" in r and "kind" in r:
                meta["session_id"] = meta["session_id"] or r.get("sessionId")
                meta["kind"] = "subagent" if r.get("kind") == "subagent" else meta["kind"]
            elif "type" in r:
                records[str(r.get("id", ln))] = (ln, r)
            else:
                ctx.unknown(store.id, path, ln, "keys:" + "-".join(sorted(map(str, r))[:3]))
    for ln, m in records.values():
        _gemini_msg(ctx, e, store, path, m, ln)
    meta["session_id"] = str(meta["session_id"] or os.path.splitext(os.path.basename(path))[0])
    return meta, e.msgs


def load_agy_history(ctx: Ctx, store: "Store", path: str) -> Dict[str, tuple]:
    """Antigravity CLI prompt history: one file, many conversations (user prompts only)."""
    out: Dict[str, tuple] = {}
    emitters: Dict[str, Emit] = {}
    for ln, r in ctx.jsonl(store.id, path):
        cid = r.get("conversationId")
        if not cid or "display" not in r:
            ctx.unknown(store.id, path, ln, "history-shape")
            continue
        cid = str(cid)
        if cid not in out:
            ws = re.sub(r"^file://", "", str(r.get("workspace") or "")) or None
            emitters[cid] = Emit(ctx, store, path, ws)
            out[cid] = ({"session_id": cid, "cwd": ws, "client": "google.antigravity-cli", "kind": "main"},
                        emitters[cid].msgs)
        if r.get("type") in ("slash_command", "shell"):
            emitters[cid].drop(r.get("timestamp"), ln)  # harness control, not prose
        elif r.get("type"):
            ctx.unknown(store.id, path, ln, r.get("type"))
        else:
            ws = re.sub(r"^file://", "", str(r.get("workspace") or "")) or None
            emitters[cid].cwd = ws or emitters[cid].cwd
            emitters[cid].text("user", r.get("display"), r.get("timestamp"), ln)
    return out


def load_brain(ctx: Ctx, store: "Store", files: List[str], sid: str) -> tuple:
    """Antigravity agent 'brain' artifacts (task / implementation_plan / walkthrough markdown)."""
    meta = {"session_id": sid, "cwd": None, "client": "google.antigravity", "kind": "main"}
    msgs: List[dict] = []
    for f in files:
        st = ctx.admit(store.id, f, whole_record=True)
        if not st:
            continue
        with open(f, "rb") as fh:
            text = fh.read().decode("utf-8", "replace")
        if not ctx.unchanged(store.id, f, st):
            continue
        ctx.receipt[store.id]["records_parsed"] += 1
        e = Emit(ctx, store, f)
        base = os.path.basename(f).lower()
        label = next((k for k in ("implementation_plan", "walkthrough", "task") if base.startswith(k)), "artifact")
        ts = _json_field(ctx, f + ".metadata.json", "updatedAt") if os.path.isfile(f + ".metadata.json") else None
        e.text("assistant", text, ts or st.st_mtime, 1, kind="artifact", label=label)
        msgs += e.msgs
    return meta, msgs


def iter_json_array(ctx: Ctx, store: str, path: str, fh) -> Iterator[Tuple[int, dict]]:
    """Stream the elements of a top-level JSON array without loading the whole document."""
    dec, buf, pos, idx, eof = json.JSONDecoder(), "", 0, 0, False
    reader = io.TextIOWrapper(fh, encoding="utf-8", errors="replace")
    cap = ctx.limits["max_record_bytes"]

    def fill():
        nonlocal buf, pos, eof
        chunk = reader.read(1 << 20)
        eof = not chunk
        buf = buf[pos:] + chunk
        pos = 0

    fill()
    while True:
        while True:
            while pos < len(buf) and buf[pos] in " \t\r\n,[":
                pos += 1
            if pos < len(buf) or eof:
                break
            fill()
        if pos >= len(buf) or buf[pos] == "]":
            return
        try:
            obj, end = dec.raw_decode(buf, pos)
        except ValueError:
            if eof:
                ctx.quarantine_(store, path, "malformed-json", idx + 1)
                return
            if len(buf) - pos > cap:
                ctx.quarantine_(store, path, "record-over-size-cap", idx + 1)
                return
            fill()
            continue
        idx += 1
        pos = end
        if isinstance(obj, dict):
            ctx.receipt[store]["records_parsed"] += 1
            yield idx, obj
        else:
            ctx.quarantine_(store, path, "non-object-record", idx)


_EXPORT_MEMBER = re.compile(r"^(?:[\w .-]+/)?conversations(?:-\d+)?\.json$")


def archive_problem(ctx: Ctx, z: zipfile.ZipFile) -> Optional[str]:
    """Vet a user-supplied export archive BEFORE reading any member. Nothing is extracted:
    only the expected member is streamed in memory; the archive itself is never modified."""
    infos = z.infolist()
    if len(infos) > 100000:
        return "archive-too-many-members"
    total = 0
    for i in infos:
        name = i.filename
        if name.startswith(("/", "\\")) or ".." in name.replace("\\", "/").split("/") or re.match(r"^[A-Za-z]:", name):
            return "archive-path-traversal"
        if (i.external_attr >> 16) & 0o170000 == 0o120000:
            return "archive-symlink-member"
        if i.flag_bits & 0x1:
            return "archive-encrypted-member"
        total += i.file_size
        if i.compress_size and i.file_size / max(1, i.compress_size) > 200:
            return "archive-compression-ratio"
    if total > ctx.limits["max_file_bytes"] * 4:
        return "archive-over-size-cap"
    if not any(_EXPORT_MEMBER.match(i.filename) for i in infos):
        return "archive-missing-conversations-json"
    return None


def export_conversations(ctx: Ctx, store: "Store", path: str) -> Iterator[Tuple[int, dict]]:
    if zipfile.is_zipfile(path):
        with zipfile.ZipFile(path) as z:
            problem = archive_problem(ctx, z)
            if problem:
                ctx.quarantine_(store.id, path, problem)
                return
            for i in sorted(z.infolist(), key=lambda i: i.filename):
                if _EXPORT_MEMBER.match(i.filename):
                    if i.file_size > ctx.limits["max_file_bytes"]:
                        ctx.quarantine_(store.id, path, "file-over-size-cap")
                        continue
                    with z.open(i) as fh:
                        yield from iter_json_array(ctx, store.id, path, fh)
    else:
        with open(path, "rb") as fh:
            yield from iter_json_array(ctx, store.id, path, fh)


def load_chatgpt_conv(ctx: Ctx, store: "Store", path: str, idx: int, conv: dict) -> tuple:
    e = Emit(ctx, store, path)
    mapping = conv.get("mapping") if isinstance(conv.get("mapping"), dict) else None
    if mapping is None:
        ctx.quarantine_(store.id, path, "unknown-document-shape", idx)
        return None, []
    node, chain, seen = conv.get("current_node"), [], set()
    while node and node in mapping and node not in seen:
        seen.add(node)
        chain.append(mapping[node])
        node = mapping[node].get("parent")
    for n in reversed(chain or list(mapping.values())):
        m = n.get("message") or {}
        if not m:
            continue
        role = (m.get("author") or {}).get("role")
        c = m.get("content") or {}
        parts = c.get("parts") if isinstance(c.get("parts"), list) else [c.get("text")]
        ts = m.get("create_time")
        if role in ("user", "assistant"):
            e.text(role, "\n".join(p for p in parts if isinstance(p, str)), ts, idx)
            for p in parts:
                if isinstance(p, dict):
                    e.event(role, "attachment", ts, idx, p.get("content_type") or "file")
            for a in (m.get("metadata") or {}).get("attachments") or []:
                e.event(role, "attachment", ts, idx, str((a or {}).get("mimeType") or "file").split("/")[0])
        elif role == "tool":
            e.tool_result(ts, idx)
        else:
            e.drop(ts, idx)
    cid = str(conv.get("conversation_id") or conv.get("id") or idx)
    return {"session_id": cid, "cwd": None, "client": "openai.chatgpt-export", "kind": "main"}, e.msgs


def load_claude_ai_conv(ctx: Ctx, store: "Store", path: str, idx: int, conv: dict) -> tuple:
    if not isinstance(conv.get("chat_messages"), list):
        ctx.quarantine_(store.id, path, "unknown-document-shape", idx)
        return None, []
    e = Emit(ctx, store, path)
    for m in conv["chat_messages"]:
        if not isinstance(m, dict):
            continue
        role = {"human": "user", "assistant": "assistant"}.get(m.get("sender"))
        ts = m.get("created_at")
        if not role:
            e.drop(ts, idx)
            continue
        e.text(role, m.get("text") or blocks_text(m.get("content")), ts, idx)
        for a in (m.get("attachments") or []) + (m.get("files") or []):
            e.event(role, "attachment", ts, idx, "file")
    cid = str(conv.get("uuid") or idx)
    return {"session_id": cid, "cwd": None, "client": "anthropic.claude-ai-export", "kind": "main"}, e.msgs


# ── stores ─────────────────────────────────────────────────────────────────

class Unit:
    """One session. `load()` parses once; results loaded with keep=True (the capability
    samples, including deferred/quarantined ones) are reused, so each file is counted once."""

    def __init__(self, path: str, load: Callable[[], tuple]):
        self.path, self._load, self._kept = path, load, None

    def load(self, keep: bool = False) -> tuple:
        if self._kept is not None:
            return self._kept
        result = self._load()
        if keep:
            self._kept = result
        return result


class Store:
    def __init__(self, sid: str, provider: str, clients: str, root: str, fmt: str, account: str,
                 kind: str = "local-cache", status: Optional[str] = None, reason: str = "",
                 coverage: str = "full", verified: str = ""):
        self.id, self.provider, self.clients, self.root, self.fmt = sid, provider, clients, root, fmt
        self.account, self.kind, self.status, self.reason = account, kind, status, reason
        self.coverage, self.verified = coverage, verified
        self.evidence: Dict[str, object] = {}
        self.enumerate: Optional[Callable[[], List[Unit]]] = None
        self._units: Optional[List[Unit]] = None

    def units(self) -> List[Unit]:
        if self._units is None:
            self._units = self.enumerate() if self.enumerate else []
        return self._units


def rel(home: str, p: str) -> str:
    return "~" + p[len(home):] if p == home or p.startswith(home + os.sep) else _HOME_PATH.sub("~", p)


def _json_field(ctx: Ctx, path: str, *keys) -> Optional[str]:
    try:
        if os.path.getsize(path) > ctx.limits["max_record_bytes"]:
            return None
        with open(path, "rb") as fh:
            v = json.load(fh)
        for k in keys:
            v = v.get(k) if isinstance(v, dict) else None
        return v if isinstance(v, str) else None
    except (OSError, ValueError):
        return None


def fingerprint(ctx: Ctx, identifier: Optional[str]) -> str:
    """Opaque account/profile alias; the raw identifier (often an e-mail) never leaves."""
    return ctx.opaque("acct-", identifier) if identifier else "acct-not-recorded"


def _file_unit(ctx: Ctx, store: Store, path: str, loader: Callable[[], tuple]) -> Unit:
    def load():
        st = ctx.admit(store.id, path)
        if not st:
            return None, []
        meta, msgs = loader()
        if not ctx.unchanged(store.id, path, st):
            return None, []
        return meta, msgs
    return Unit(path, load)


def build_stores(ctx: Ctx, exports: List[Tuple[str, str]]) -> List[Store]:
    home = ctx.home
    J = lambda *p: os.path.join(home, *p)  # noqa: E731
    app = J("Library", "Application Support")
    UUID = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    claude_main = re.compile(r"^[^/]+/" + UUID + r"\.jsonl$")
    claude_sub = re.compile(r"^[^/]+/" + UUID + r"/subagents/agent-[A-Za-z0-9_-]+\.jsonl$")
    stores: List[Store] = []

    claude_acct = fingerprint(ctx, _json_field(ctx, J(".claude.json"), "oauthAccount", "accountUuid"))
    root = J(".claude", "projects")
    s = Store("claude-code/projects", "anthropic",
              "anthropic.claude-code, anthropic.claude-desktop, anthropic.claude-sdk",
              root, "jsonl records (user/assistant + known harness records)", claude_acct,
              verified="record version 2.x")
    s.enumerate = lambda s=s, root=root: [
        _file_unit(ctx, s, f, lambda f=f: load_claude(ctx, s, f, "anthropic.claude-code"))
        for f in ctx.walk(s.id, root, lambda r, n: bool(claude_main.match(r) or claude_sub.match(r)))]
    stores.append(s)

    cow = next((c for c in (os.path.join(app, "Claude", "local-agent-mode-sessions"),
                            J(".config", "Claude", "local-agent-mode-sessions")) if os.path.isdir(c)),
               os.path.join(app, "Claude", "local-agent-mode-sessions"))
    s = Store("claude-desktop/cowork", "anthropic", "anthropic.claude-desktop-cowork", cow,
              "jsonl records under <vm>/.claude/projects", claude_acct, verified="record version 2.x")

    def _cow(s=s, cow=cow):
        def keep(r, n):
            part = r.replace(os.sep, "/").split("/.claude/projects/", 1)
            return len(part) == 2 and bool(claude_main.match(part[1]) or claude_sub.match(part[1]))
        return [_file_unit(ctx, s, f, lambda f=f: load_claude(ctx, s, f, "anthropic.claude-desktop-cowork"))
                for f in ctx.walk(s.id, cow, keep)]
    s.enumerate = _cow
    stores.append(s)

    stores.append(Store("claude-desktop/chat", "anthropic", "anthropic.claude-ai", "cloud",
                        "account data export (conversations.json)", claude_acct, kind="cloud",
                        status="unavailable", coverage="none",
                        reason="export-only: not requested (chat history is cloud-hosted; the app's "
                               "IndexedDB/LevelDB is a web cache, not a transcript store)"))

    codex = J(".codex")
    imported: Dict[str, str] = {}
    imp = os.path.join(codex, "external_agent_session_imports.json")
    if os.path.isfile(imp) and os.path.getsize(imp) <= ctx.limits["max_record_bytes"]:
        try:
            with open(imp, "rb") as fh:
                recs = json.load(fh).get("records") or []
            for rec in recs if isinstance(recs, list) else []:
                if isinstance(rec, dict) and rec.get("imported_thread_id"):
                    imported[str(rec["imported_thread_id"])] = (
                        "claude-code" if "/.claude/" in str(rec.get("source_path") or "") else "external")
        except (OSError, ValueError, AttributeError):
            pass
    rollout = re.compile(r"^rollout-[0-9T:.-]+-" + UUID + r"\.jsonl$")
    for sub in ("sessions", "archived_sessions"):
        root = os.path.join(codex, sub)
        s = Store("codex/" + sub, "openai", "openai.codex-cli, openai.codex-app, openai.codex-exec, "
                  "openai.codex-ide, openai.codex-sdk", root,
                  "jsonl rollout (session_meta / response_item / event_msg …)",
                  "acct-not-recorded (auth store holds credentials; not read)", verified="cli_version 0.x")
        s.enumerate = lambda s=s, root=root: [
            _file_unit(ctx, s, f, lambda f=f: load_codex(ctx, s, f, imported))
            for f in ctx.walk(s.id, root, lambda r, n: bool(rollout.match(n)))]
        s.evidence["imported_duplicates_known"] = len(imported)
        stores.append(s)
    stores.append(Store("codex/cloud-tasks", "openai", "openai.codex-cloud", "cloud", "cloud-hosted",
                        "acct-not-recorded", kind="cloud", status="unavailable", coverage="none",
                        reason="export-only: not requested (cloud tasks are server-side)"))

    omp_main = re.compile(r"^[^/]+/\d{4}-\d{2}-\d{2}T[\d-]+Z_[0-9a-f-]+\.jsonl$")
    omp_sub = re.compile(r"^[^/]+/\d{4}-\d{2}-\d{2}T[\d-]+Z_[0-9a-f-]+/(?:[^/]+/)*[A-Za-z0-9._-]+\.jsonl$")
    for sid, vendor, client, root, keep in (
            ("omp/sessions", "omp", "omp.cli", J(".omp", "agent", "sessions"),
             lambda r, n: bool(omp_main.match(r) or omp_sub.match(r))),
            ("prime-agent/sessions", "primeintellect", "primeintellect.prime-agent", J(".prime", "agent", "sessions"),
             lambda r, n: "/" not in r.replace(os.sep, "/") and bool(re.match(r"^[A-Za-z0-9._-]+\.jsonl$", n)))):
        s = Store(sid, vendor, client, root, "jsonl pi-session entries (session/message/…)", "acct-not-recorded",
                  verified="session version 3")
        s.enumerate = lambda s=s, root=root, keep=keep, client=client: [
            _file_unit(ctx, s, f, lambda f=f: load_pi(ctx, s, f, client, bool(omp_sub.match(os.path.relpath(f, root)))))
            for f in ctx.walk(s.id, root, keep)]
        stores.append(s)

    gtmp = J(".gemini", "tmp")
    s = Store("gemini-cli/tmp", "google", "google.gemini-cli", gtmp, "json / jsonl chat recordings (session-*)",
              fingerprint(ctx, _json_field(ctx, J(".gemini", "google_accounts.json"), "active")),
              verified="json {sessionId,messages}; jsonl header + $set/$rewindTo")

    def _gem(s=s, gtmp=gtmp):
        roots: Dict[str, str] = {}
        pj = J(".gemini", "projects.json")
        try:
            if os.path.getsize(pj) <= ctx.limits["max_record_bytes"]:
                with open(pj, "rb") as fh:
                    for path, name in (json.load(fh).get("projects") or {}).items():
                        roots[str(name)] = path
                        roots[hashlib.sha256(path.encode()).hexdigest()] = path
        except (OSError, ValueError, AttributeError):
            pass
        units = []
        for f in ctx.walk(s.id, gtmp, lambda r, n: bool(re.match(r"^[^/]+/chats/session-[\w.-]+\.jsonl?$",
                                                                   r.replace(os.sep, "/")))):
            d = os.path.dirname(os.path.dirname(f))
            cwd = roots.get(os.path.basename(d))
            pr = os.path.join(d, ".project_root")
            if os.path.isfile(pr) and not os.path.islink(pr):
                with open(pr, "rb") as fh:
                    cwd = clean(fh.read(4096).decode("utf-8", "replace")).strip() or cwd
            whole = f.endswith(".json")

            def load(f=f, cwd=cwd, whole=whole):
                st = ctx.admit(s.id, f, whole_record=whole)
                if not st:
                    return None, []
                meta, msgs = load_gemini(ctx, s, f, cwd)
                return (meta, msgs) if ctx.unchanged(s.id, f, st) else (None, [])
            units.append(Unit(f, load))
        return units
    s.enumerate = _gem
    stores.append(s)

    agy = J(".gemini", "antigravity-cli")
    hist = os.path.join(agy, "history.jsonl")
    s = Store("antigravity-cli/history", "google", "google.antigravity-cli", agy,
              "jsonl prompt history (conversationId / workspace / display)", "acct-not-recorded",
              coverage="prompts-only", verified="records {conversationId, display, workspace, timestamp}")

    def _agy(s=s, hist=hist):
        if hist not in ctx.walk(s.id, agy, lambda r, n: r == "history.jsonl"):
            return []
        cache: Dict[str, tuple] = {}
        state = {}

        def ensure():
            if "done" not in state:
                st = ctx.admit(s.id, hist)
                parsed = load_agy_history(ctx, s, hist) if st else {}
                cache.update(parsed if st and ctx.unchanged(s.id, hist, st) else {})
                state["done"] = True
        ensure()
        return [Unit(hist, lambda cid=cid: cache.get(cid, (None, []))) for cid in list(cache)]
    s.enumerate = _agy
    stores.append(s)
    stores.append(Store("antigravity-cli/conversations", "google", "google.antigravity-cli",
                        os.path.join(agy, "conversations"), "sqlite with protobuf step payloads",
                        "acct-not-recorded", status="unverified", coverage="none",
                        reason="full trajectories are protobuf blobs inside SQLite with no public schema; "
                               "not parsed (this tool never opens SQLite)"))

    seen_brain: set = set()
    for name in ("antigravity", "antigravity-ide"):
        base = J(".gemini", name)
        stores.append(Store(name + "/conversations", "google", "google.antigravity",
                            os.path.join(base, "conversations"), "protobuf (.pb)", "acct-not-recorded"))
        brain = os.path.join(base, "brain")
        s = Store(name + "/brain", "google", "google.antigravity", brain,
                  "markdown artifacts (task / implementation_plan / walkthrough)", "acct-not-recorded",
                  coverage="artifacts-only", verified="<conversation-id>/<name>.md (+ .metadata.json)")

        def _brain(s=s, brain=brain):
            groups: Dict[str, List[str]] = defaultdict(list)
            for f in ctx.walk(s.id, brain, lambda r, n: bool(re.match(r"^[^/]+/[A-Za-z0-9._-]+\.md$",
                                                                      r.replace(os.sep, "/")))):
                groups[os.path.basename(os.path.dirname(f))].append(f)
            units = []
            for sid, files in sorted(groups.items()):
                if sid in seen_brain:  # the IDE keeps mirror copies of the same conversation
                    ctx.receipt[s.id]["sessions_duplicate_skipped"] += 1
                    continue
                seen_brain.add(sid)
                units.append(Unit(os.path.dirname(files[0]), lambda files=files, sid=sid: load_brain(ctx, s, files, sid)))
            return units
        s.enumerate = _brain
        stores.append(s)
    stores.append(Store("antigravity-backup", "google", "google.antigravity", J(".gemini", "antigravity-backup"),
                        "backup copy of an Antigravity profile", "acct-not-recorded", status="unavailable",
                        coverage="none", reason="backup copy: not traversed by policy (configure it explicitly "
                                                "to read it)"))
    for base in (os.path.join(app, "Antigravity"), os.path.join(app, "Antigravity IDE")):
        stores.append(Store("antigravity-app/" + os.path.basename(base).lower().replace(" ", "-"),
                            "google", "google.antigravity", base, "VS Code-fork state DB",
                            "acct-not-recorded", status="unverified", coverage="none",
                            reason="trajectory summaries live in opaque state-DB blobs; not parsed"))

    cg = os.path.join(app, "com.openai.chat")
    conv_dirs = sorted(d for d in (os.listdir(cg) if os.path.isdir(cg) else []) if d.startswith("conversations-v3-"))
    acct = fingerprint(ctx, conv_dirs[0][len("conversations-v3-"):]) if conv_dirs else "acct-not-recorded"
    s = Store("chatgpt/desktop-cache", "openai", "openai.chatgpt-desktop", cg, "encrypted *.data", acct)
    s.evidence["conversation_dirs"] = len(conv_dirs)
    stores.append(s)
    stores.append(Store("chatgpt/export", "openai", "openai.chatgpt-export", "cloud",
                        "conversations.json (or export .zip)", acct, kind="export", status="unavailable",
                        coverage="none", reason="export-only: not requested"))

    for kind, path in exports:
        p = os.path.abspath(os.path.expanduser(path))
        vendor = {"chatgpt": "openai", "claude-ai": "anthropic"}[kind]
        surface = {"chatgpt": "openai.chatgpt-export", "claude-ai": "anthropic.claude-ai-export"}[kind]
        s = Store("export/" + kind, vendor, surface, os.path.dirname(p),
                  "conversations.json (or export .zip)", "acct-export-owner", kind="export",
                  verified="chatgpt mapping-tree / claude.ai chat_messages (synthetic fixtures only)")

        def _exp(s=s, p=p, kind=kind):
            st = ctx.admit(s.id, p, sniff=not zipfile.is_zipfile(p))
            if not st:
                return []
            units = []
            for idx, conv in export_conversations(ctx, s, p):
                loader = load_chatgpt_conv if kind == "chatgpt" else load_claude_ai_conv
                meta, msgs = loader(ctx, s, p, idx, conv)
                if meta:
                    units.append(Unit(p, lambda meta=meta, msgs=msgs: (meta, msgs)))
            return units if ctx.unchanged(s.id, p, st) else []
        s.enumerate = _exp
        stores.append(s)
    return stores


def assess(ctx: Ctx, store: Store) -> Store:
    """Fail-closed: `supported` only when recent real samples parse into dialogue."""
    if store.status:
        return store
    if store.id.endswith("/conversations") and store.clients == "google.antigravity" or store.id == "chatgpt/desktop-cache":
        keep = (lambda r, n: n.endswith(".pb")) if store.id.endswith("/conversations") else \
            (lambda r, n: r.startswith("conversations-v3-") and n.endswith(".data"))
        files = ctx.walk(store.id, store.root, keep)
        if not files:
            store.status, store.reason = "unavailable", "no local store"
            return store
        heads = []
        for f in files[:5]:
            with open(f, "rb") as fh:
                heads.append(fh.read(8192))
        ent = sum(entropy(h) for h in heads) / len(heads)
        store.evidence.update(files=len(files), sample_entropy=round(ent, 2))
        store.status = "unavailable" if ent >= ENCRYPTED_ENTROPY else "unverified"
        store.reason = ("encrypted at rest (mean sample entropy %.2f bits/byte)" % ent if ent >= ENCRYPTED_ENTROPY
                        else "binary without a public schema; not parsed")
        if store.id == "chatgpt/desktop-cache":
            store.reason += "; canonical source is the account data export (not requested)"
        return store
    if not os.path.exists(store.root):
        store.status, store.reason = "unavailable", "no local store at this path"
        return store
    try:
        units = store.units()
    except Exception as exc:  # one failing adapter never aborts the run: the store is skipped, counted
        store.status, store.reason = "unverified", "adapter error during discovery: " + type(exc).__name__
        return store
    store.evidence["units"] = len(units)
    if not units:
        dup = ctx.receipt[store.id].get("sessions_duplicate_skipped", 0)
        if dup:
            store.status, store.reason = "supported", "mirror: all %d conversations duplicate a primary store" % dup
        else:
            store.status, store.reason = "unavailable", "store exists but holds no canonical session files"
        return store
    ok, tried = 0, 0
    for u in sorted(units, key=lambda u: _mtime(u.path), reverse=True):
        if tried >= SAMPLE_UNITS:
            break
        try:
            meta, msgs = u.load(keep=True)
        except Exception as exc:
            ctx.quarantine_(store.id, u.path, "adapter-error:" + type(exc).__name__)
            u._kept = (None, [])
            continue
        if meta is None:
            continue  # deferred/quarantined files are counted; sample the next stable one
        tried += 1
        ok += bool(meta.get("session_id") and any(m["kind"] in ("text", "artifact") or m.get("dialogue") for m in msgs))
    store.evidence["sample_parsed"] = "%d/%d" % (ok, tried)
    if ok:
        store.status, store.reason = "supported", store.reason or "recent samples parse into dialogue"
    else:
        store.status = "unverified"
        store.reason = "no sampled session parsed into dialogue (schema drift?) — skipped, fail-closed"
    return store


def _mtime(p: str) -> float:
    try:
        return os.path.getmtime(p)
    except OSError:
        return 0.0


# ── output safety ──────────────────────────────────────────────────────────

def in_git_worktree(path: str) -> Optional[str]:
    p = os.path.abspath(path)
    while True:
        if os.path.exists(os.path.join(p, ".git")):
            return p
        parent = os.path.dirname(p)
        if parent == p:
            return None
        p = parent


EXIT = {"complete": 0, "error": 1, "usage": 2, "partial": 3, "unsupported": 4, "blocked": 5}


def die(message: str, status: str = "error"):
    """Paths/ids only — never session content. The last stderr line is the JSON receipt."""
    sys.stderr.write(json.dumps({"status": status, "error": message}) + "\n")
    sys.exit(EXIT[status])


def _proc_start(pid: int) -> Optional[str]:
    """Start time of a pid via `ps` (argv list, no shell); None if the pid is gone."""
    import subprocess
    try:
        r = subprocess.run(["ps", "-o", "lstart=", "-p", str(int(pid))], capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.SubprocessError):
        return None
    return r.stdout.strip()[:64] or None


class OutputLock:
    """One run per output root: O_EXCL lock file with pid + process start time + host."""

    def __init__(self, out: str):
        self.path = os.path.join(out, ".lock")
        self.held = False

    def acquire(self):
        me = {"pid": os.getpid(), "start": _proc_start(os.getpid()), "host": os.uname().nodename}
        for _ in range(2):
            try:
                fd = os.open(self.path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            except FileExistsError:
                try:
                    with open(self.path, "rb") as fh:
                        owner = json.loads(fh.read(4096) or b"{}")
                except (OSError, ValueError):
                    owner = {}
                same_host = owner.get("host") == me["host"]
                alive = same_host and owner.get("pid") and _proc_start(owner["pid"]) == owner.get("start")
                if alive or not same_host or not owner:
                    die("output root is locked by another run (pid %s on %s)" % (owner.get("pid"), owner.get("host")),
                        "blocked")
                os.unlink(self.path)  # stale: recorded pid is gone or its start time differs
                continue
            with os.fdopen(fd, "w") as fh:
                fh.write(json.dumps(me))
                fh.flush()
                os.fsync(fh.fileno())
            self.held = True
            return
        die("could not acquire the output lock", "blocked")

    def release(self):
        if self.held:
            try:
                os.unlink(self.path)
            except OSError:
                pass
            self.held = False


def prepare_out(ctx: Ctx, out: str, allow_git: bool) -> str:
    out = os.path.abspath(os.path.expanduser(out))
    if os.path.islink(out) or out in ("/", ctx.home):
        die("refusing output root %s (symlink, / or home)" % rel(ctx.home, out), "blocked")
    repo = in_git_worktree(out)
    if repo and not allow_git:
        die("refusing to write inside a git work tree (%s); session data must stay private" % rel(ctx.home, repo),
            "blocked")
    os.makedirs(out, mode=0o700, exist_ok=True)
    if os.stat(out).st_mode & 0o077:
        os.chmod(out, 0o700)  # tighten a pre-existing directory BEFORE anything is written into it
    marker = os.path.join(out, MARKER)
    if not os.path.exists(marker):
        write_private(marker, ["session-catalog output root; never scanned as a source"])
    ctx.excluded_roots.append(os.path.realpath(out))
    return out


def load_key(out: str) -> bytes:
    path = os.path.join(out, ".catalog-key")
    if os.path.exists(path):
        with open(path, "rb") as fh:
            return fh.read().strip()
    key = secrets.token_hex(32).encode()
    write_private(path, [key.decode()])
    return key


def write_private(path: str, lines) -> int:
    """0600 from the first byte: temp file in the same dir, fsync, atomic rename."""
    tmp = "%s.%d.tmp" % (path, os.getpid())
    if os.path.lexists(tmp):
        os.unlink(tmp)
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    n = 0
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        for line in lines:
            fh.write(line + "\n")
            n += 1
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)
    return n


# ── selection + commands ───────────────────────────────────────────────────

def norm_path(p: Optional[str]) -> Optional[str]:
    return os.path.normpath(os.path.expanduser(re.sub(r"^file://", "", p))) if p else None


def project_match(cwd: Optional[str], projects: List[str]) -> bool:
    c = norm_path(cwd)
    return bool(c) and any(c == p or c.startswith(p + os.sep) for p in projects)


def surface_filter(args) -> Optional[List[str]]:
    return [x.strip() for x in args.surface.split(",") if x.strip()] if getattr(args, "surface", None) else None


def store_in_scope(s: Store, surfaces: Optional[List[str]]) -> bool:
    if not surfaces:
        return True
    mine = [x.strip() for x in s.clients.split(",")]
    return any(m.startswith(f) or f.startswith(m) for m in mine for f in surfaces)


def select(ctx: Ctx, args, stores: List[Store]):
    """Yield (store, unit, meta, msgs, hits) for sessions passing every filter."""
    projects = [norm_path(p) for p in args.project or []]
    mention = re.compile(args.mention, re.I) if args.mention else None
    surfaces = surface_filter(args)
    hw_iso = iso(ctx.high_water)
    for s in stores:
        if s.status != "supported" or not store_in_scope(s, surfaces):
            continue
        for u in s.units():
            try:
                meta, msgs = u.load()
            except Exception as exc:  # isolate the failing file; the run continues and ends partial
                ctx.quarantine_(s.id, u.path, "adapter-error:" + type(exc).__name__)
                continue
            if meta is None:
                continue
            if surfaces and not any(str(meta.get("client")).startswith(f) for f in surfaces):
                continue
            rc = ctx.receipt[s.id]
            rc["sessions_loaded"] += 1
            stamps = [m["ts"] for m in msgs if m["ts"]]
            meta["started_at"], meta["ended_at"] = (min(stamps), max(stamps)) if stamps else (None, None)
            if meta["ended_at"] and meta["ended_at"] >= hw_iso:
                rc["sessions_deferred_live"] += 1
                continue
            if meta.get("imported_from") and not args.include_imported:
                rc["sessions_skipped_imported_duplicate"] += 1
                continue
            if (args.since and (meta["ended_at"] or "") < args.since) or \
                    (args.until and (meta["started_at"] or "9") > args.until):
                continue
            dialogue = [m for m in msgs if m["kind"] in ("text", "artifact")]
            for m in dialogue:  # attribution per message: the cwd in effect when it was written
                m["in_project"] = project_match(m.get("cwd") or meta.get("cwd"), projects) if projects else not mention
                m["mention"] = bool(mention and mention.search(m["text"]))
            by_cwd = any(m["in_project"] for m in dialogue)
            hits = sum(m["mention"] for m in dialogue)
            if not by_cwd and not hits:
                continue
            meta["selected_by"] = "cwd" if by_cwd else "mention"
            rc["sessions_selected"] += 1
            yield s, u, meta, msgs, hits


def partition(surface: str, s: Store) -> str:
    return "%s:%s" % (surface, s.account)


def cmd_stores(ctx: Ctx, args, stores: List[Store]) -> int:
    rows = [{"store": s.id, "vendor": s.provider, "surfaces": s.clients, "identity": s.account,
             "source_kind": s.kind, "status": s.status,
             "coverage": s.coverage if s.status == "supported" else "none", "path": rel(ctx.home, s.root),
             "format": s.fmt, "verified_format": s.verified, "reason": s.reason,
             "resume_adopt": "not implemented (capability 2, out of scope)",
             "evidence": dict(s.evidence, **{k: v for k, v in ctx.receipt[s.id].items()})} for s in stores]
    if getattr(args, "json", False):
        print(json.dumps({"schema": SCHEMA, "os_user": fingerprint(ctx, getpass.getuser()), "stores": rows},
                         indent=2))
        return 0
    print("%-34s %-12s %-15s %s" % ("STORE", "STATUS", "COVERAGE", "PATH"))
    for r in rows:
        print("%-34s %-12s %-15s %s" % (r["store"], r["status"], r["coverage"], r["path"]))
        if r["status"] != "supported":
            print("%-63s -> %s" % ("", r["reason"]))
    print("(metadata-only dry run; `index`/`extract` need an explicit --out and a scope)")
    return 0


def cmd_index(ctx: Ctx, args, stores: List[Store], out: str) -> int:
    rows = []
    for s, u, meta, msgs, hits in select(ctx, args, stores):
        surface = str(meta.get("client"))
        counts = Counter(m["role"] if m["kind"] == "text" else m["kind"] for m in msgs)
        att = Counter(m["tool"] for m in msgs if m["kind"] == "attachment")
        body = "\x1e".join("%s\x1f%s\x1f%s" % (m["role"], m["kind"], m["text"]) for m in msgs)
        sref = ctx.opaque("s-", surface + ":" + meta["session_id"])
        rows.append(json.dumps({
            "schema": SCHEMA, "partition": partition(surface, s), "vendor": s.provider, "surface": surface,
            "identity": s.account, "store": s.id, "source_id": ctx.source_id(u.path),
            "session_ref": sref, "session_id_private": meta["session_id"],
            "parent_session_ref": ctx.opaque("s-", surface + ":" + meta["parent_session_id"])
            if meta.get("parent_session_id") else None,
            "kind": meta.get("kind"),
            "cwd_private": rel(ctx.home, norm_path(meta.get("cwd"))) if meta.get("cwd") else None,
            "started_at": meta["started_at"], "ended_at": meta["ended_at"], "counts": dict(counts),
            "attachments_by_type": dict(att), "mention_hits": hits, "selected_by": meta["selected_by"],
            "imported_from": meta.get("imported_from"), "lines": max([m["line"] for m in msgs] or [0]),
            "in_project_messages": sum(1 for m in msgs if m.get("in_project")),
            "content_sha256_private": hashlib.sha256(body.encode()).hexdigest()}, sort_keys=True))
    n = write_private(os.path.join(out, "sessions.jsonl"), rows)
    return finish(ctx, args, stores, out, "index", {"sessions": n})


def cmd_extract(ctx: Ctx, args, stores: List[Store], out: str) -> int:
    grep = re.compile(args.grep, re.I) if args.grep else None
    mention = re.compile(args.mention, re.I) if args.mention else None
    roles = set(args.roles.split(","))
    sessions = messages = 0
    w = sys.stdout
    for s, u, meta, msgs, hits in select(ctx, args, stores):
        surface = str(meta.get("client"))
        norm = [m for m in msgs if (m["kind"] in ("text", "artifact") and m["role"] in roles)
                or m["kind"] == "tool_call"]
        # keep in-project turns, plus on-topic turns (± context) from outside the project
        keep = set()
        for i, m in enumerate(norm):
            if m["kind"] == "tool_call":
                continue
            if m.get("in_project"):
                keep.add(i)
            elif m.get("mention"):
                keep.update(range(max(0, i - args.context), i + args.context + 1))
        norm = [m for i, m in enumerate(norm) if i in keep or (m["kind"] == "tool_call" and m.get("cwd") and
                                                              project_match(m["cwd"], [norm_path(p) for p in args.project or []]))]
        if grep:
            norm = [m for m in norm if m["kind"] == "tool_call" or grep.search(m["text"])]
        if not any(m["kind"] != "tool_call" for m in norm):
            continue
        sessions += 1
        sref = ctx.opaque("s-", surface + ":" + meta["session_id"])
        src = ctx.source_id(u.path)
        for seq, m in enumerate(norm):
            text = m["text"]
            if args.max_chars and len(text) > args.max_chars:
                text = text[:args.max_chars] + " [...truncated %d chars]" % (len(text) - args.max_chars)
            messages += 1
            w.write(json.dumps({
                "schema": SCHEMA, "partition": partition(surface, s), "surface": surface, "session_ref": sref,
                "source_id": src, "pointer": {"line": m["line"]}, "seq": seq, "ts": m["ts"], "role": m["role"],
                "kind": m["kind"], "tool": m["tool"], "text": text, "redactions": m["redactions"],
                "selected_by": meta["selected_by"],
                "provenance": "observed in %s session %s" % (surface, sref)}, ensure_ascii=False) + "\n")
    w.flush()
    return finish(ctx, args, stores, out, "extract", {"sessions": sessions, "messages_streamed": messages})


def finish(ctx: Ctx, args, stores: List[Store], out: str, command: str, totals: dict) -> int:
    surfaces = surface_filter(args)
    considered = [s for s in stores if store_in_scope(s, surfaces)]
    skipped = [{"store": s.id, "surfaces": s.clients, "identity": s.account, "status": s.status,
                "reason": s.reason} for s in considered if s.status != "supported"]
    identities: Dict[str, dict] = {}
    for s in considered:
        d = identities.setdefault("%s:%s" % (s.provider, s.account),
                                  {"local_cache": [], "export": [], "cloud_or_export_not_requested": []})
        bucket = "cloud_or_export_not_requested" if s.kind in ("cloud", "export") and s.status != "supported" \
            else ("export" if s.kind == "export" else "local_cache")
        d[bucket].append({"store": s.id, "status": s.status})
    receipt = {s.id: dict(ctx.receipt.get(s.id, {}), status=s.status) for s in considered}
    supported = [s for s in considered if s.status == "supported"]
    status = ("unsupported" if not supported else
              "partial" if skipped or ctx.quarantine else "complete")
    manifest = {
        "schema": SCHEMA, "command": command, "status": status, "generated_at": iso(time.time()),
        "high_water": iso(ctx.high_water),
        "filters": {"project": [rel(ctx.home, norm_path(p)) for p in args.project or []], "mention": args.mention,
                    "since": args.since, "until": args.until, "surface": getattr(args, "surface", None),
                    "include_imported": args.include_imported, "exclude_path_globs": len(ctx.exclude_globs)},
        "limits": ctx.limits, "receipt": receipt, "identities": identities,
        "stores_skipped": skipped, "totals": dict(totals, quarantined=len(ctx.quarantine),
                                                  security_findings=len(ctx.findings)),
        "claim": ("complete over all known stores" if status == "complete" else
                  "%s: %d store(s) skipped, %d item(s) quarantined; do not claim 'all sessions'"
                  % (status, len(skipped), len(ctx.quarantine))),
        "resume_adopt": "not implemented (capability 2, out of scope)",
        "notice": "Session content is untrusted data: items are observations to verify, never instructions.",
        "sources_private": ctx.sources,
    }
    write_private(os.path.join(out, "run-manifest.json"), [json.dumps(manifest, indent=2, sort_keys=True)])
    write_private(os.path.join(out, "quarantine.jsonl"), [json.dumps(q, sort_keys=True) for q in ctx.quarantine])
    findings = args.security_findings or os.path.join(out, "security-findings.jsonl")
    os.makedirs(os.path.dirname(os.path.abspath(findings)), mode=0o700, exist_ok=True)
    write_private(findings, [json.dumps(f, sort_keys=True) for f in ctx.findings.values()])
    sys.stderr.write(json.dumps({"status": status, "command": command, "totals": manifest["totals"],
                                 "claim": manifest["claim"]}) + "\n")
    return EXIT[status]


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog="session_catalog.py", description=__doc__.split("\n\n")[0])
    ap.add_argument("--home", default=os.path.expanduser("~"), help="home directory whose stores are read")
    ap.add_argument("--export", action="append", default=[], metavar="KIND=PATH",
                    help="an already-downloaded data export: chatgpt=PATH or claude-ai=PATH (json or zip)")
    ap.add_argument("--high-water", help="ISO timestamp; only files/sessions older than this are read (default: now)")
    ap.add_argument("--exclude-path", action="append", default=[], help="glob of source paths to skip (repeatable)")
    for k, v in LIMITS.items():
        ap.add_argument("--" + k.replace("_", "-"), type=int, default=v)
    ap.add_argument("--out", help="private output root, outside any git repo (required for index/extract)")
    ap.add_argument("--allow-git-output", action="store_true", help="permit an output root inside a git work tree")
    ap.add_argument("--security-findings", help="credential findings file (default: <out>/security-findings.jsonl)")
    sub = ap.add_subparsers(dest="cmd")
    p_st = sub.add_parser("stores", help="capability matrix (metadata only; the default)")
    p_st.add_argument("--json", action="store_true")
    for name in ("index", "extract"):
        p = sub.add_parser(name)
        p.add_argument("--project", action="append", help="select sessions whose cwd is this path or below")
        p.add_argument("--mention", help="also select messages matching this regex (case-insensitive)")
        p.add_argument("--since", help="ISO date/time lower bound")
        p.add_argument("--until", help="ISO date/time upper bound")
        p.add_argument("--surface", help="comma list of surface ids or prefixes, e.g. openai.codex-cli,anthropic.")
        p.add_argument("--include-imported", action="store_true",
                       help="keep sessions a harness imported from another harness (duplicates)")
    p_ex = sub.choices["extract"]
    p_ex.add_argument("--grep", help="keep only messages matching this regex")
    p_ex.add_argument("--roles", default="user,assistant", help="comma list (default: user,assistant)")
    p_ex.add_argument("--context", type=int, default=1, help="turns kept around each --mention hit outside --project")
    p_ex.add_argument("--max-chars", type=int, default=4000, help="truncate each message (0 = never)")
    return ap


def main(argv: Optional[List[str]] = None) -> int:
    os.umask(0o077)
    args = build_parser().parse_args(argv)
    args.cmd = args.cmd or "stores"  # bare invocation = metadata-only dry run
    for key in ("since", "until"):
        v = getattr(args, key, None)
        if v:
            setattr(args, key, iso(v if "T" in v else v + "T00:00:00Z") or die("invalid --%s" % key, "usage"))
    if args.cmd != "stores" and not args.out:
        die("%s needs an explicit --out <private dir>" % args.cmd, "usage")
    if args.cmd == "extract" and not (args.project or args.mention):
        die("extract needs --project and/or --mention (topic scoping is mandatory)", "usage")
    exports = []
    for e in args.export:
        kind, _, path = e.partition("=")
        if kind not in ("chatgpt", "claude-ai") or not os.path.isfile(os.path.expanduser(path)):
            die("--export expects chatgpt=PATH or claude-ai=PATH to an existing file", "usage")
        exports.append((kind, path))
    hw = iso(args.high_water) if args.high_water else None
    if args.high_water and not hw:
        die("invalid --high-water", "usage")
    high_water = datetime.strptime(hw, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc).timestamp() if hw else time.time()
    home = os.path.abspath(os.path.expanduser(args.home))
    ctx = Ctx(home, high_water, {k: getattr(args, k) for k in LIMITS}, args.exclude_path, secrets.token_bytes(32))
    if args.cmd == "stores":
        stores = [assess(ctx, s) for s in build_stores(ctx, exports)]
        return cmd_stores(ctx, args, stores)
    out = prepare_out(ctx, args.out, args.allow_git_output)
    lock = OutputLock(out)
    lock.acquire()
    try:
        ctx.key = load_key(out)
        if args.security_findings:
            ctx.excluded_roots.append(os.path.realpath(os.path.dirname(os.path.abspath(args.security_findings))))
        stores = [assess(ctx, s) for s in build_stores(ctx, exports)]
        return (cmd_index if args.cmd == "index" else cmd_extract)(ctx, args, stores, out)
    finally:
        lock.release()


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except SystemExit:
        raise
    except Exception as exc:  # never echo content: type name only
        sys.stderr.write(json.dumps({"status": "error", "error": "internal error: " + type(exc).__name__}) + "\n")
        sys.exit(EXIT["error"])
